
package com.systemlogic;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ONEWAY", targetNamespace = "http://systemlogic.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ONEWAY {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnAddResult", targetNamespace = "http://systemlogic.com/", className = "com.systemlogic.ReturnAddResult")
    @ResponseWrapper(localName = "returnAddResultResponse", targetNamespace = "http://systemlogic.com/", className = "com.systemlogic.ReturnAddResultResponse")
    @Action(input = "http://systemlogic.com/ONEWAY/returnAddResultRequest", output = "http://systemlogic.com/ONEWAY/returnAddResultResponse")
    public int returnAddResult(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "adding", targetNamespace = "http://systemlogic.com/", className = "com.systemlogic.Adding")
    @Action(input = "http://systemlogic.com/ONEWAY/adding")
    public void adding(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
