
package com.systemlogic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ONEWAYService", targetNamespace = "http://systemlogic.com/", wsdlLocation = "http://localhost:8090/Oneway/ONEWAY?wsdl")
public class ONEWAYService
    extends Service
{

    private final static URL ONEWAYSERVICE_WSDL_LOCATION;
    private final static WebServiceException ONEWAYSERVICE_EXCEPTION;
    private final static QName ONEWAYSERVICE_QNAME = new QName("http://systemlogic.com/", "ONEWAYService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/Oneway/ONEWAY?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ONEWAYSERVICE_WSDL_LOCATION = url;
        ONEWAYSERVICE_EXCEPTION = e;
    }

    public ONEWAYService() {
        super(__getWsdlLocation(), ONEWAYSERVICE_QNAME);
    }

    public ONEWAYService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ONEWAYSERVICE_QNAME, features);
    }

    public ONEWAYService(URL wsdlLocation) {
        super(wsdlLocation, ONEWAYSERVICE_QNAME);
    }

    public ONEWAYService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ONEWAYSERVICE_QNAME, features);
    }

    public ONEWAYService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ONEWAYService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ONEWAY
     */
    @WebEndpoint(name = "ONEWAYPort")
    public ONEWAY getONEWAYPort() {
        return super.getPort(new QName("http://systemlogic.com/", "ONEWAYPort"), ONEWAY.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ONEWAY
     */
    @WebEndpoint(name = "ONEWAYPort")
    public ONEWAY getONEWAYPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://systemlogic.com/", "ONEWAYPort"), ONEWAY.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ONEWAYSERVICE_EXCEPTION!= null) {
            throw ONEWAYSERVICE_EXCEPTION;
        }
        return ONEWAYSERVICE_WSDL_LOCATION;
    }

}
